In [1]:
import numpy as np
from IBHP_sim import IBHP
from collections import Counter
from particle_filter import transfer_multi_dist_res2vec
from tqdm import tqdm

In [5]:
ibhp = IBHP()
ibhp.generate_data(n_sample=10)

n=1时主题数量为0，重新生成主题数量
n=1时主题数量: 4
n=1时主题出现情况: [[1. 1. 1. 1.]]
n=1时base kernel的权重：[[0.80678312 0.81759494 0.43422624 0.06213638]
 [0.17109213 0.00923928 0.0522199  0.43497405]
 [0.02212475 0.17316579 0.51355385 0.50288957]]
n=1时的base kernel：[1. 2. 3.]
n=1时的factor kernel all：[1.21534162 1.35557085 2.07932761 2.44075318]
n=1时的factor kernel：[[1.21534162 1.35557085 2.07932761 2.44075318]]
n=1时的词分布：[[2.07490207e-020 1.52595611e-102 4.06886159e-059 1.07652706e-015]
 [1.21613178e-139 2.68772482e-068 2.19682881e-007 4.55616050e-085]
 [7.15641009e-025 3.25226601e-176 4.55361715e-015 1.99394537e-011]
 [4.73583827e-045 4.49860371e-014 7.79895057e-053 5.42738381e-086]
 [1.45391571e-046 1.27430606e-047 8.35103774e-010 5.46346991e-021]
 [1.66704438e-013 4.58918297e-004 5.35306211e-087 4.57904916e-006]
 [2.44989973e-079 2.60284632e-108 1.81084999e-006 3.69726399e-014]
 [1.84645599e-056 4.67827922e-008 6.63352673e-046 6.95860353e-017]
 [6.92961833e-002 2.79874774e-042 7.93790008e-037 6.07486498e-041]
 [6

In [3]:
T = transfer_multi_dist_res2vec(ibhp.T)
T

array([[ 4, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 23, 44, 44, 46,
        46, 46, 87, 87],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 46, 46, 46, 46, 46,
        46, 46, 87, 87],
       [ 4, 12, 12, 12, 12, 12, 12, 12, 12, 12, 44, 44, 44, 44, 44, 46,
        46, 46, 87, 87],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 33, 44,
        46, 46, 46, 87],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        38, 44, 44, 44],
       [12, 12, 12, 12, 12, 20, 20, 20, 20, 20, 20, 20, 29, 38, 44, 44,
        44, 46, 46, 87],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 18, 20, 20, 38,
        44, 44, 46, 46],
       [ 4, 20, 20, 20, 20, 20, 20, 20, 20, 33, 46, 46, 46, 46, 46, 46,
        46, 46, 87, 87],
       [12, 12, 12, 12, 12, 12, 12, 20, 20, 20, 20, 44, 44, 46, 46, 46,
        46, 46, 87, 87],
       [12, 12, 12, 12, 12, 12, 12, 20, 20, 20, 20, 38, 44, 46, 46, 46,
        46, 46, 46, 84]])

In [4]:
np.arange(2, 101)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])